### ISSUE TITLE
Google drive upload not working

### ISSUE THREAD

**Issue by gauravsuman007** [shakilofficial0/Heroku-CyberTOR#11]
I have successfully connected my Google drive folder (I can see the contents of my gdrive folder in the Drive tab)
Unfortunately, the downloaded ISO is not being uploaded to drive

I'm using the Web UI for my use case and just downloaded a 2.1 GB ubuntu ISO from thepiratebay
Also, when I click on the Download button after the download is complete, I don't see any google drive status txt file (as mentioned in the README), the downloaded folder is there but the file is no longer present inside so I can't even download it directly from Heroku.

Any ideas what may be going wrong here?

Thanks

**Comment by shakilofficial0** [comment]
can you provide me the config you set in heroku?

and can you give me you web address
??
