### ISSUE TITLE
TG Bot not responding

### ISSUE THREAD

**Issue by sh4feen007** [shakilofficial0/Heroku-CyberTOR#7]
I have set env variables correctly restarted all dynos multiple times. 
Sent /start /help to my bot but  it's not responding.

Logs:
app[web.1]: Bot ready
app[web.1]: web allowed
app[web.1]: > Running on http://localhost:xxxx
app[web.1]: 
app[web.1]: Gdrive client up

**Comment by shakilofficial0** [comment]
https://www.youtube.com/watch?v=ODU7r_itcX8

i think it will help you out

**Comment by sh4feen007** [comment]
I didn't expect this sort of reply.
Thanks anyway.
Bot is broken.

**Comment by shakilofficial0** [comment]
I dont know but Everyone's Bot is working fine
what should i say here
but after all
you can give me more info
I will try to help you

**Comment by sh4feen007** [comment]
Hi dev,
Thanks for reconsidering it!
Actually I have set every env vars correctly and in the log it's showing "bot ready" but on the other side the bot isn't responding to aby of my comnands /start /help /status etc etc none of the comnands!
I have tried re creating the app on heroku before opening this issue.
Thanks.

**Comment by shakilofficial0** [comment]
try the base one
"https://github.com/patheticGeek/torrent-aio-bot"
and inform me that everything is fine or not

**Comment by sh4feen007** [comment]
Bot doesn't even start on the base one I tried that before finding this repo
