### ISSUE TITLE
How to remove Password?

### ISSUE THREAD

**Issue by gcp-amri** [shakilofficial0/Heroku-CyberTOR#9]
How to remove Password?

**Comment by argantor** [comment]
Any update yet?

**Comment by shakilofficial0** [comment]
yes you can remove it

**Comment by shakilofficial0** [comment]
Just remove it 

<script>
           var user1= "alpha";
var username=prompt('Please Log in. Username:',' ');
if (username==user1){
   var pass1= "alpha";
   password=prompt('If you are suppose to be here you have a password. Please type it now:',' ');
    if (password==pass1){
        alert("correct!")
     }
    else {
        window.location="403error";
    }
}
else {
  window.location="403error";
}
        </script>
        
        
        from Heroku-CyberTOR/web/public/index.html
